/**
 * Usage Settings Article
 */

import { KBCallout } from '@/components/knowledge-base/KBCallout';

export default function UsageArticle() {
  return (
    <>
      <p>
        The Usage page shows how your team is using Pilot. Monitor conversations, 
        messages, and API calls to understand your usage patterns.
      </p>

      <h2 id="accessing-usage">Accessing Usage</h2>
      <ol>
        <li>Click <strong>Settings</strong> in the sidebar</li>
        <li>Select the <strong>Usage</strong> tab</li>
      </ol>

      <KBCallout variant="info">
        Usage information is available to users with Billing permissions.
      </KBCallout>

      <h2 id="usage-metrics">Usage Metrics</h2>

      <h3 id="conversations">Conversations</h3>
      <p>
        Track how many conversations Ari handles:
      </p>
      <ul>
        <li><strong>Total conversations:</strong> All conversations in the period</li>
        <li><strong>AI-handled:</strong> Conversations fully handled by Ari</li>
        <li><strong>Human takeovers:</strong> Conversations requiring human intervention</li>
      </ul>

      <h3 id="messages">Messages</h3>
      <p>
        Monitor message volume:
      </p>
      <ul>
        <li><strong>Total messages:</strong> All messages sent and received</li>
        <li><strong>AI messages:</strong> Responses generated by Ari</li>
        <li><strong>Visitor messages:</strong> Messages from your visitors</li>
      </ul>

      <h3 id="api-calls">API Calls</h3>
      <p>
        If using the API:
      </p>
      <ul>
        <li><strong>Total API calls:</strong> Requests to the Pilot API</li>
        <li><strong>By endpoint:</strong> Breakdown by API endpoint</li>
        <li><strong>Rate limit status:</strong> Current usage vs. limits</li>
      </ul>

      <h2 id="time-periods">Time Periods</h2>
      <p>
        View usage across different periods:
      </p>
      <ul>
        <li><strong>Current period:</strong> Since your last billing date</li>
        <li><strong>Previous periods:</strong> Historical usage data</li>
        <li><strong>Custom range:</strong> Select specific dates</li>
      </ul>

      <h2 id="usage-trends">Understanding Trends</h2>
      <p>
        Look for patterns in your usage:
      </p>
      <ul>
        <li><strong>Peak hours:</strong> When visitors are most active</li>
        <li><strong>Growth:</strong> How usage changes over time</li>
        <li><strong>Efficiency:</strong> AI resolution rate trends</li>
      </ul>

      <KBCallout variant="tip">
        Rising takeover rates might indicate gaps in Ari's knowledge. 
        Review conversations to identify areas for improvement.
      </KBCallout>

      <h2 id="plan-limits">Plan Limits</h2>
      <p>
        Your plan includes usage allowances:
      </p>
      <ul>
        <li>See your current usage vs. plan limits</li>
        <li>Receive warnings when approaching limits</li>
        <li>Upgrade if you need more capacity</li>
      </ul>

      <h2 id="optimizing-usage">Optimizing Usage</h2>
      <ul>
        <li>Improve Ari's knowledge to reduce takeovers</li>
        <li>Add help articles for common questions</li>
        <li>Review low-quality conversations for training</li>
        <li>Optimize API calls in custom integrations</li>
      </ul>

      <h2 id="exporting-data">Exporting Usage Data</h2>
      <p>
        Export usage data for reporting:
      </p>
      <ul>
        <li>Download CSV files of usage metrics</li>
        <li>Include in business reports</li>
        <li>Track ROI of your Ari deployment</li>
      </ul>
    </>
  );
}
