-- Delete the placeholder data and insert data for the actual user
DELETE FROM public.client_onboarding_links WHERE user_id = '00000000-0000-0000-0000-000000000001'::uuid;
DELETE FROM public.scope_of_works WHERE user_id = '00000000-0000-0000-0000-000000000001'::uuid;
DELETE FROM public.onboarding_submissions WHERE user_id = '00000000-0000-0000-0000-000000000001'::uuid;

-- Insert sample client onboarding links for the actual user
INSERT INTO public.client_onboarding_links (user_id, client_name, company_name, email, industry, onboarding_url, status, sow_status, date_sent, last_activity, personal_note) VALUES
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Sarah Johnson', 'Mountain View RV Park', 'sarah@mountainviewrv.com', 'RV Park/Resort', 'https://onboarding.example.com/mvrvp', 'Completed', 'SOW Generated', NOW() - INTERVAL '5 days', NOW() - INTERVAL '1 day', 'Great project scope, ready for development phase'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Michael Chen', 'Sunset Manufacturing', 'michael@sunsetmfg.com', 'Manufactured Home Community', 'https://onboarding.example.com/sunset', 'In Progress', NULL, NOW() - INTERVAL '8 days', NOW() - INTERVAL '2 days', 'Follow up on target audience details'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Jessica Rodriguez', 'Elite Capital Partners', 'jessica@elitecapital.com', 'Capital & Syndication Company', 'https://onboarding.example.com/elite', 'SOW Generated', 'Client Review', NOW() - INTERVAL '10 days', NOW() - INTERVAL '1 hour', 'High-value client, priority project'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'David Miller', 'Local Plumbing Pro', 'david@localplumbingpro.com', 'Local Business (Service-Based)', 'https://onboarding.example.com/plumbing', 'Approved', 'Approved', NOW() - INTERVAL '12 days', NOW() - INTERVAL '3 hours', 'Simple service website, quick turnaround'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Amanda Foster', 'National Tech Solutions', 'amanda@nationaltech.com', 'National Business', 'https://onboarding.example.com/nts', 'Sent', NULL, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', 'Waiting for initial response'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Robert Thompson', 'Riverside Communities', 'robert@riversidecomm.com', 'Manufactured Home Community', 'https://onboarding.example.com/riverside', 'In Progress', NULL, NOW() - INTERVAL '18 days', NOW() - INTERVAL '4 days', 'Need clarification on community features'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Lisa Anderson', 'Premier Investment Group', 'lisa@premierinvest.com', 'Capital & Syndication Company', 'https://onboarding.example.com/premier', 'Completed', 'SOW Generated', NOW() - INTERVAL '20 days', NOW() - INTERVAL '2 hours', 'Complex investment platform requirements');

-- Insert sample scope of works for the actual user
INSERT INTO public.scope_of_works (user_id, client, client_contact, email, industry, project_type, title, content, status, pages, integrations, date_created, date_modified) VALUES
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Mountain View RV Park', 'Sarah Johnson', 'sarah@mountainviewrv.com', 'RV Park/Resort', 'Website Development', 'RV Park Website & Booking System', 'Comprehensive website with online booking, amenity showcase, and guest management system for Mountain View RV Park.', 'Approved', 8, '{"Stripe", "Google Maps", "Email Marketing"}', NOW() - INTERVAL '3 days', NOW() - INTERVAL '1 day'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Elite Capital Partners', 'Jessica Rodriguez', 'jessica@elitecapital.com', 'Capital & Syndication Company', 'Investment Platform', 'Capital Syndication Platform', 'Advanced investment platform with investor portal, document management, and automated reporting for real estate syndications.', 'Client Review', 12, '{"DocuSign", "Plaid", "AWS S3", "Stripe"}', NOW() - INTERVAL '5 days', NOW() - INTERVAL '2 hours'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Local Plumbing Pro', 'David Miller', 'david@localplumbingpro.com', 'Local Business (Service-Based)', 'Service Website', 'Plumbing Service Website', 'Local service website with appointment booking, service area mapping, and customer review system.', 'Agency Review', 5, '{"Google Calendar", "Google Maps", "Twilio"}', NOW() - INTERVAL '7 days', NOW() - INTERVAL '1 day'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Riverside Communities', 'Robert Thompson', 'robert@riversidecomm.com', 'Manufactured Home Community', 'Community Portal', 'Community Management Portal', 'Resident portal with lease management, maintenance requests, and community event coordination.', 'Draft', 10, '{"Stripe", "SendGrid", "Twilio"}', NOW() - INTERVAL '2 days', NOW() - INTERVAL '6 hours'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Premier Investment Group', 'Lisa Anderson', 'lisa@premierinvest.com', 'Capital & Syndication Company', 'Investment Platform', 'Multi-Asset Investment Platform', 'Enterprise-grade investment platform supporting multiple asset classes with advanced analytics and reporting.', 'Draft', 15, '{"Bloomberg API", "Plaid", "DocuSign", "AWS S3", "Stripe"}', NOW() - INTERVAL '1 day', NOW() - INTERVAL '4 hours');

-- Insert sample onboarding submissions for the actual user
INSERT INTO public.onboarding_submissions (user_id, client_name, client_email, project_type, description, timeline, budget_range, industry, status, submitted_at) VALUES
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Sarah Johnson', 'sarah@mountainviewrv.com', 'Website Development', 'Need a modern website with online booking system for our RV park', '3-4 months', '$10,000 - $25,000', 'RV Park/Resort', 'approved', NOW() - INTERVAL '5 days'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Jessica Rodriguez', 'jessica@elitecapital.com', 'Investment Platform', 'Complex real estate syndication platform with investor management', '6-8 months', '$50,000+', 'Capital & Syndication Company', 'approved', NOW() - INTERVAL '10 days'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'David Miller', 'david@localplumbingpro.com', 'Service Website', 'Simple service website with appointment booking', '2-3 months', '$5,000 - $10,000', 'Local Business (Service-Based)', 'approved', NOW() - INTERVAL '12 days'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Michael Chen', 'michael@sunsetmfg.com', 'Community Portal', 'Manufactured home community website with resident features', '4-5 months', '$25,000 - $50,000', 'Manufactured Home Community', 'pending', NOW() - INTERVAL '8 days'),
('cfdcde65-d8cc-45c3-8512-1155ceb041da'::uuid, 'Lisa Anderson', 'lisa@premierinvest.com', 'Investment Platform', 'Enterprise investment platform for multiple asset classes', '8-12 months', '$50,000+', 'Capital & Syndication Company', 'approved', NOW() - INTERVAL '20 days');