-- Insert sample request data without assigned_to field
INSERT INTO public.requests (
  id,
  title,
  description,
  status,
  priority,
  client_name,
  client_email,
  company_name,
  website_name,
  website_url,
  user_id,
  due_date,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Update homepage banner',
  'Change the main banner image and text to reflect new branding',
  'to_do'::request_status,
  'high'::request_priority,
  'Sarah Johnson',
  'sarah@acmecorp.com',
  'Acme Corp',
  'Acme Corp Website',
  'https://acmecorp.com',
  '11111111-1111-1111-1111-111111111111'::uuid,
  now() + interval '7 days',
  now() - interval '2 days',
  now() - interval '1 day'
),
(
  gen_random_uuid(),
  'Fix contact form validation',
  'Contact form is not properly validating email addresses and phone numbers',
  'in_progress'::request_status,
  'urgent'::request_priority,
  'Mike Chen',
  'mike@techsolutions.com',
  'Tech Solutions',
  'Tech Solutions Portal',
  'https://techsolutions.com',
  '11111111-1111-1111-1111-111111111111'::uuid,
  now() + interval '3 days',
  now() - interval '5 days',
  now() - interval '2 hours'
),
(
  gen_random_uuid(),
  'Add new product catalog page',
  'Create a dedicated page for the new product line with filtering and search',
  'on_hold'::request_status,
  'medium'::request_priority,
  'Jennifer Adams',
  'jen@startupxyz.com',
  'StartupXYZ',
  'StartupXYZ Commerce',
  'https://startupxyz.com',
  '11111111-1111-1111-1111-111111111111'::uuid,
  now() + interval '14 days',
  now() - interval '1 week',
  now() - interval '3 days'
),
(
  gen_random_uuid(),
  'Update company logo across site',
  'Replace old logo with new brand identity across all pages and favicons',
  'completed'::request_status,
  'low'::request_priority,
  'Robert Wilson',
  'rob@globalinc.com',
  'Global Inc',
  'Global Inc Corporate',
  'https://globalinc.com',
  '11111111-1111-1111-1111-111111111111'::uuid,
  now() - interval '2 days',
  now() - interval '2 weeks',
  now() - interval '1 day'
),
(
  gen_random_uuid(),
  'Implement SSL certificate',
  'Setup and configure SSL certificate for secure HTTPS connection',
  'to_do'::request_status,
  'high'::request_priority,
  'Lisa Brown',
  'lisa@securesite.com',
  'SecureSite LLC',
  'SecureSite Platform',
  'https://securesite.com',
  '11111111-1111-1111-1111-111111111111'::uuid,
  now() + interval '5 days',
  now() - interval '1 day',
  now() - interval '6 hours'
),
(
  gen_random_uuid(),
  'Mobile responsive fixes',
  'Fix mobile layout issues on product pages and checkout flow',
  'in_progress'::request_status,
  'medium'::request_priority,
  'David Kim',
  'david@mobilefirst.com',
  'MobileFirst Co',
  'MobileFirst Store',
  'https://mobilefirst.com',
  '11111111-1111-1111-1111-111111111111'::uuid,
  now() + interval '10 days',
  now() - interval '3 days',
  now() - interval '4 hours'
);