-- Seed remaining articles (Part 2)

-- Ari: Lead Capture
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published)
VALUES ('ari', 'lead-capture', 'Lead Capture', 'Configure contact forms to collect visitor information.', '<p>Ari can capture visitor information before starting a conversation. Configure a contact form to collect leads and qualify visitors automatically.</p><h2 id="how-it-works">How Lead Capture Works</h2><p>When enabled, visitors see a contact form before they can chat.</p><div data-callout data-callout-type="tip">Checkbox labels support rich text, making them perfect for terms and conditions agreements.</div><div data-related-articles data-articles=''[{"categoryId":"leads","articleSlug":"overview","title":"Lead Management"}]''></div>', 4, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;

-- Ari: Knowledge Sources
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published)
VALUES ('ari', 'knowledge-sources', 'Knowledge Sources', 'Train Ari with your business information.', '<p>Knowledge sources are how Ari learns about your business. The more relevant information you provide, the better Ari can assist your visitors.</p><h2 id="types-of-sources">Types of Knowledge Sources</h2><ul><li><strong>Website URLs</strong> – Point Ari to your website pages</li><li><strong>Documents</strong> – Upload PDFs, Word documents, or other files</li><li><strong>Manual Text</strong> – Directly enter information</li></ul><div data-callout data-callout-type="tip">Add your most frequently asked questions first – these will have the biggest immediate impact.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"overview","title":"Understanding Ari"}]''></div>', 5, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;

-- Ari: Locations, Help Articles, Announcements, News, Custom Tools, Webhooks, Integrations, API Access, Installation
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published) VALUES
('ari', 'locations', 'Locations', 'Configure multiple business locations.', '<p>If your business has multiple locations, configure each one so Ari can provide location-specific information.</p><div data-callout data-callout-type="tip">Include the timezone for each location to ensure appointments are scheduled correctly.</div><div data-related-articles data-articles=''[{"categoryId":"planner","articleSlug":"overview","title":"Using the Planner"}]''></div>', 6, true),
('ari', 'help-articles', 'Help Articles', 'Create self-service documentation.', '<p>Help Articles are a self-service knowledge base that appears in the chat widget.</p><div data-callout data-callout-type="tip">Well-organized help articles reduce repetitive questions.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"knowledge-sources","title":"Knowledge Sources"}]''></div>', 7, true),
('ari', 'announcements', 'Announcements', 'Display promotional banners in the widget.', '<p>Announcements are eye-catching banners that appear at the top of the chat widget.</p><div data-callout data-callout-type="tip">Use high-contrast colors and concise text.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"news","title":"News"}]''></div>', 8, true),
('ari', 'news', 'News', 'Share updates and blog posts in the widget.', '<p>The News feature lets you share updates, blog posts, and stories directly in the chat widget.</p><div data-callout data-callout-type="info">Only enable the News tab if you plan to publish content regularly.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"announcements","title":"Announcements"}]''></div>', 9, true),
('ari', 'custom-tools', 'Custom Tools', 'Extend Ari with external APIs.', '<p>Custom Tools extend Ari''s capabilities by connecting to external services and APIs.</p><div data-callout data-callout-type="warning">Custom Tools require technical knowledge.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"webhooks","title":"Webhooks"}]''></div>', 10, true),
('ari', 'webhooks', 'Webhooks', 'Receive notifications when events happen.', '<p>Webhooks allow Pilot to notify your external systems when events happen.</p><div data-callout data-callout-type="info">Unlike APIs where you request data, webhooks push data to you automatically.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"custom-tools","title":"Custom Tools"}]''></div>', 11, true),
('ari', 'integrations', 'Integrations', 'Connect Pilot to your existing tools.', '<p>Connect Pilot to your existing tools and services like Google Calendar.</p><div data-callout data-callout-type="info">Calendar integrations enable real-time availability checking.</div><div data-related-articles data-articles=''[{"categoryId":"planner","articleSlug":"overview","title":"Using the Planner"}]''></div>', 12, true),
('ari', 'api-access', 'API Access', 'Interact with Ari programmatically.', '<p>The Pilot API allows developers to interact with Ari programmatically.</p><div data-callout data-callout-type="warning">API Access is an advanced feature intended for developers.</div><div data-callout data-callout-type="info">Store your API key securely. Never expose it in client-side code.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"webhooks","title":"Webhooks"}]''></div>', 13, true),
('ari', 'installation', 'Installing the Widget', 'Deploy Ari to your website.', '<p>Once you''ve configured Ari, it''s time to install the widget on your website.</p><div data-callout data-callout-type="info">The embed code should be placed just before the closing &lt;/body&gt; tag.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"appearance","title":"Customizing Appearance"}]''></div>', 14, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;

-- Inbox articles
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published) VALUES
('inbox', 'overview', 'Managing Conversations', 'View and manage all visitor conversations.', '<p>The Inbox is where you manage all conversations between Ari and your visitors.</p><div data-callout data-callout-type="tip">Translation works automatically based on detected language.</div><div data-related-articles data-articles=''[{"categoryId":"inbox","articleSlug":"takeover","title":"Human Takeover"}]''></div>', 0, true),
('inbox', 'takeover', 'Human Takeover', 'Take control of conversations from Ari.', '<p>The takeover feature lets you seamlessly step in and take control of a conversation.</p><div data-callout data-callout-type="info">When you take over, Ari stops responding automatically.</div><div data-related-articles data-articles=''[{"categoryId":"inbox","articleSlug":"overview","title":"Managing Conversations"}]''></div>', 1, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;

-- Leads articles
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published) VALUES
('leads', 'overview', 'Lead Management', 'Track and organize captured leads.', '<p>The Leads section helps you manage and track potential customers.</p><div data-callout data-callout-type="tip">Customize your stages to match your sales process.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"lead-capture","title":"Lead Capture Settings"}]''></div>', 0, true),
('leads', 'stages', 'Lead Stages', 'Organize leads through your sales process.', '<p>Lead stages help you organize and track leads through your sales process.</p><div data-callout data-callout-type="tip">Keep your stage count manageable – 5-7 stages is ideal.</div><div data-related-articles data-articles=''[{"categoryId":"leads","articleSlug":"overview","title":"Lead Management"}]''></div>', 1, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;

-- Planner articles
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published) VALUES
('planner', 'overview', 'Using the Planner', 'Manage appointments and events.', '<p>The Planner helps you manage appointments, showings, and events.</p><div data-callout data-callout-type="info">Events from connected calendars sync automatically.</div><div data-related-articles data-articles=''[{"categoryId":"ari","articleSlug":"custom-tools","title":"Custom Tools"}]''></div>', 0, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;

-- Analytics articles  
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published) VALUES
('analytics', 'overview', 'Analytics Overview', 'Track Ari''s performance and insights.', '<p>The Analytics section gives you insights into how Ari is performing.</p><div data-callout data-callout-type="tip">Use peak time data to ensure your team is available during high-traffic periods.</div><div data-related-articles data-articles=''[{"categoryId":"analytics","articleSlug":"report-builder","title":"Report Builder"}]''></div>', 0, true),
('analytics', 'report-builder', 'Report Builder', 'Create comprehensive reports.', '<p>The Report Builder helps you create comprehensive reports to share with your team.</p><div data-callout data-callout-type="tip">Start with a focused report featuring 2-3 sections.</div><div data-related-articles data-articles=''[{"categoryId":"analytics","articleSlug":"overview","title":"Analytics Overview"}]''></div>', 1, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;

-- Settings articles
INSERT INTO platform_hc_articles (category_id, slug, title, description, content, order_index, is_published) VALUES
('settings', 'general', 'General Settings', 'Organization information and branding.', '<p>General settings control your organization''s basic information.</p><div data-callout data-callout-type="info">This information may appear on invoices and reports.</div><div data-related-articles data-articles=''[{"categoryId":"settings","articleSlug":"profile","title":"Profile Settings"}]''></div>', 0, true),
('settings', 'profile', 'Profile Settings', 'Your personal information and preferences.', '<p>Your profile contains your personal information and preferences.</p><div data-callout data-callout-type="tip">Use a clear, professional photo.</div><div data-related-articles data-articles=''[{"categoryId":"settings","articleSlug":"general","title":"General Settings"}]''></div>', 1, true),
('settings', 'team', 'Managing Your Team', 'Invite and manage team members.', '<p>Invite team members to collaborate on Pilot.</p><div data-callout data-callout-type="info">Invitations expire after 7 days.</div><div data-related-articles data-articles=''[{"categoryId":"settings","articleSlug":"general","title":"General Settings"}]''></div>', 2, true),
('settings', 'billing', 'Billing & Subscription', 'Manage payments and invoices.', '<p>Manage your Pilot subscription, update payment methods, and view invoices.</p><div data-callout data-callout-type="info">When you upgrade, you''re immediately charged a prorated amount.</div><div data-related-articles data-articles=''[{"categoryId":"settings","articleSlug":"usage","title":"Usage"}]''></div>', 3, true),
('settings', 'usage', 'Usage', 'View usage metrics and limits.', '<p>The Usage page shows how your team is using Pilot.</p><div data-callout data-callout-type="tip">Rising takeover rates might indicate gaps in Ari''s knowledge.</div><div data-related-articles data-articles=''[{"categoryId":"settings","articleSlug":"billing","title":"Billing & Subscription"}]''></div>', 4, true),
('settings', 'notifications', 'Notification Preferences', 'Configure how and when you''re notified.', '<p>Control how and when Pilot notifies you about important events.</p><div data-callout data-callout-type="tip">Enable email notifications for critical events you shouldn''t miss.</div><div data-related-articles data-articles=''[{"categoryId":"settings","articleSlug":"team","title":"Managing Your Team"}]''></div>', 5, true),
('settings', 'sessions', 'Active Sessions', 'Manage your login sessions.', '<p>Sessions show you where your account is currently logged in.</p><div data-callout data-callout-type="warning">If you see a session you don''t recognize, sign it out immediately and change your password.</div><div data-related-articles data-articles=''[{"categoryId":"settings","articleSlug":"profile","title":"Profile Settings"}]''></div>', 6, true)
ON CONFLICT (category_id, slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, content = EXCLUDED.content, order_index = EXCLUDED.order_index, is_published = EXCLUDED.is_published;